services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
      - rag_app
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
        - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
    expose:
      - "3000"
    env_file:
      - ./.env
    environment:
      - NEXT_PRIVATE_API_URL=http://backend:4000
      - NEXT_PUBLIC_API_URL=/api
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - RAG_SERVICE_URL=http://rag_app:8001
      - PUBLIC_URLS=http://localhost,https://localhost,http://ec2-18-189-195-81.us-east-2.compute.amazonaws.com,https://ec2-18-189-195-81.us-east-2.compute.amazonaws.com
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "4000"
    env_file:
      - ./.env
    environment:
      - PORT=4000
      - FRONTEND_URL=http://frontend:3000
      - PUBLIC_URL=http://ec2-18-189-195-81.us-east-2.compute.amazonaws.com
      - NODE_ENV=production
      - NPM_CONFIG_PRODUCTION=true
      - NODE_OPTIONS=--max-old-space-size=2048
      - RAG_SERVICE_URL=http://rag_app:8001
      - ALLOWED_ORIGINS=http://localhost,https://localhost,http://ec2-18-189-195-81.us-east-2.compute.amazonaws.com,https://ec2-18-189-195-81.us-east-2.compute.amazonaws.com
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - rag_app
    networks:
      - app-network
    restart: always

  rag_app:
    build:
      context: ./rag
      dockerfile: Dockerfile
    expose:
      - "8001"
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - uploads_data:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads_data: