services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - uploads_data:/app/uploads:ro
    depends_on:
      - frontend
      - backend
      - rag_upload
      - rag_query
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
        - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
    expose:
      - "3000"
    env_file:
      - ./.env
    environment:
      - NEXT_PRIVATE_API_URL=http://backend:4000
      - NEXT_PUBLIC_API_URL=/api
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - RAG_SERVICE_URL=http://rag_query:8001
      - PUBLIC_URLS=http://localhost,https://localhost,http://ec2-18-189-195-81.us-east-2.compute.amazonaws.com,https://ec2-18-189-195-81.us-east-2.compute.amazonaws.com
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "4000"
    env_file:
      - ./.env
    environment:
      - PORT=4000
      - FRONTEND_URL=http://frontend:3000
      - PUBLIC_URL=http://ec2-18-189-195-81.us-east-2.compute.amazonaws.com
      - NODE_ENV=production
      - NPM_CONFIG_PRODUCTION=true
      - NODE_OPTIONS=--max-old-space-size=2048
      - RAG_UPLOAD_URL=http://rag_upload:8000
      - RAG_QUERY_URL=http://rag_query:8001
      - ALLOWED_ORIGINS=http://localhost,https://localhost,http://ec2-18-189-195-81.us-east-2.compute.amazonaws.com,https://ec2-18-189-195-81.us-east-2.compute.amazonaws.com
    volumes:
      - uploads_data:/app/uploads:rw
    depends_on:
      - rag_upload
      - rag_query
    networks:
      - app-network
    restart: always

  rag_upload:
    build:
      context: ./rag
      dockerfile: Dockerfile.upload
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - PINECONE_ENV=${PINECONE_ENV}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost,https://localhost,http://ec2-18-189-195-81.us-east-2.compute.amazonaws.com,https://ec2-18-189-195-81.us-east-2.compute.amazonaws.com}
    volumes:
      - uploads_data:/app/uploads:rw
    networks:
      - app-network
    restart: always

  rag_query:
    build:
      context: ./rag
      dockerfile: Dockerfile.query
    expose:
      - "8001"
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - PINECONE_ENV=${PINECONE_ENV}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost,https://localhost,http://ec2-18-189-195-81.us-east-2.compute.amazonaws.com,https://ec2-18-189-195-81.us-east-2.compute.amazonaws.com}
    volumes:
      - uploads_data:/app/uploads:ro
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  uploads_data:
    driver: local