version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - PORT=4000
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=development

  upload_service:
    build:
      context: ./rag
      args:
        INSTALL_JUPYTER: false
    env_file:
      - ./rag/.env
    volumes:
      - ./rag:/app
    command: python upload.py

  rag_app:
    build:
      context: ./rag
      args:
        INSTALL_JUPYTER: false
    ports:
      - "8000:8000"
    env_file:
      - ./rag/.env
    volumes:
      - ./rag:/app
    command: python main.py
    restart: always

  jupyter:
    build:
      context: ./rag
      args:
        INSTALL_JUPYTER: true
    ports:
      - "8888:8888"
    env_file:
      - ./rag/.env
    volumes:
      - ./rag:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root