services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NEXT_PRIVATE_API_URL=http://localhost:4000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - RAG_SERVICE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - PORT=4000
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=development
      - NPM_CONFIG_PRODUCTION=false
      - NODE_OPTIONS=--max-old-space-size=2048
      - RAG_SERVICE_URL=http://localhost:8000
      - ALLOWED_ORIGINS=http://localhost:3000
    command: npm run dev
    depends_on:
      - rag_app
    networks:
      - app-network

  rag_app:
    build:
      context: ./rag
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./rag:/app
      - /app/__pycache__
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 