version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PRIVATE_API_URL=http://backend:4000
      - NEXT_PUBLIC_API_URL=http://localhost/api
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - PORT=4000
      - FRONTEND_URL=http://localhost:3000
      - PUBLIC_URL=http://localhost
      - NODE_ENV=development
    networks:
      - app-network

  upload_service:
    build:
      context: ./rag
      args:
        INSTALL_JUPYTER: false
    env_file:
      - ./rag/.env
    volumes:
      - ./rag:/app
    command: python upload.py
    networks:
      - app-network

  rag_app:
    build:
      context: ./rag
      args:
        INSTALL_JUPYTER: false
    ports:
      - "8000:8000"
    env_file:
      - ./rag/.env
    volumes:
      - ./rag:/app
    command: python main.py
    restart: always
    networks:
      - app-network

  jupyter:
    build:
      context: ./rag
      args:
        INSTALL_JUPYTER: true
    ports:
      - "8888:8888"
    env_file:
      - ./rag/.env
    volumes:
      - ./rag:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge