version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
      - rag_app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PRIVATE_API_URL=http://backend:4000
      - NEXT_PUBLIC_API_URL=http://localhost/api
      - RAG_SERVICE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - PORT=4000
      - FRONTEND_URL=http://localhost:3000
      - PUBLIC_URL=http://localhost
      - NODE_ENV=development
      - RAG_SERVICE_URL=http://rag_app:8000
    depends_on:
      - rag_app
    networks:
      - app-network

  rag_app:
    build:
      context: ./rag
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./rag/.env
    volumes:
      - ./rag:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge