version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      # For server-side API calls (internal Docker network)
      - NEXT_PRIVATE_API_URL=http://backend:4000
      # For client-side API calls (through Nginx)
      - NEXT_PUBLIC_API_URL=/api
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "4000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=4000
      # For internal service communication
      - FRONTEND_URL=http://frontend:3000
      # For generating public URLs in API responses
      - PUBLIC_URL=http://ec2-18-222-164-243.us-east-2.compute.amazonaws.com
      - NODE_ENV=production
      - NPM_CONFIG_PRODUCTION=true
      - NODE_OPTIONS="--max-old-space-size=2048"
    networks:
      - app-network
    restart: always

  upload_service:
    build:
      context: ./rag
      args:
        INSTALL_JUPYTER: false
    env_file:
      - ./rag/.env
    command: python upload.py
    networks:
      - app-network
    restart: on-failure

  rag_app:
    build:
      context: ./rag
      args:
        INSTALL_JUPYTER: false
    expose:
      - "8000"
    env_file:
      - ./rag/.env
    command: python main.py
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge