version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
      - rag_app
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file:
      - ./frontend/.env.local
    environment:
      - NEXT_PRIVATE_API_URL=http://backend:4000
      - NEXT_PUBLIC_API_URL=/api
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - RAG_SERVICE_URL=http://rag_app:8000
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "4000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=4000
      - FRONTEND_URL=http://frontend:3000
      - PUBLIC_URL=http://ec2-18-222-164-243.us-east-2.compute.amazonaws.com
      - NODE_ENV=production
      - NPM_CONFIG_PRODUCTION=true
      - NODE_OPTIONS="--max-old-space-size=2048"
      - RAG_SERVICE_URL=http://rag_app:8000
    depends_on:
      - rag_app
    networks:
      - app-network
    restart: always

  rag_app:
    build:
      context: ./rag
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - ./rag/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge