services:
  upload_service:
    build:
      args:
        INSTALL_JUPYTER: false
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - PINECONE_INDEX=${PINECONE_INDEX}
    volumes:
      - .:/app
    command: python upload.py
  rag_app:
    build:
      args:
        INSTALL_JUPYTER: false
    ports:
      - "8000:8000"
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - PINECONE_INDEX=${PINECONE_INDEX}
    volumes:
      - .:/app
    command: python main.py
    restart: always
  jupyter:
    build:
      args:
        INSTALL_JUPYTER: true
    ports:
      - "8888:8888"
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - PINECONE_INDEX=${PINECONE_INDEX}
    volumes:
      - .:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
